- name: allow access to port vbmc ports from undercloud managment network
  become: True
  iptables:
      action: insert
      comment: "OCP Edge VMs: vbmc ports"
      table: filter
      chain: INPUT
      jump: ACCEPT
      protocol: "udp"
      source: "{{  hostvars[vbmc_host]['ansible_'+ipmi_net].ipv4.address }}/{{  hostvars[vbmc_host]['ansible_'+ipmi_net].ipv4.netmask }}"
      destination_port: "{{ item.1 }}"
  with_nested:
      - "{{ vbmc_ports.items() }}"
