---
- name: Install helper tools
  delegate_to: localhost
  become: true
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - 'python3-dns'
    - 'python3-netaddr'

- name: set EXTERNAL_SUBNET
  set_fact:
    extcidrnet: "{{ ip | ipaddr('network') }}/{{ ip | ipaddr('prefix') }}"
  vars:
    ip: "{{ ansible_default_ipv4.address }}/{{ansible_default_ipv4.netmask }}"

- name: Get openshift_version from job.components
  set_fact:
    version: "{{ item['name'] }}"
  with_items: "{{ hostvars.localhost.job_info.job.components }}"
  when: item["type"] == "ocp"

- set_fact:
    build: "{{ hostvars.localhost.job_info.job.topic.data.build }}"
    pullsecret: "{{ openshift_secret | default(hostvars.localhost.job_info.job.topic.data.pull_secret)| to_json }}"
