---
- name: set EXTERNAL_SUBNET
  set_fact:
    extcidrnet: "{{ ip | ipaddr('network') }}/{{ ip | ipaddr('prefix') }}"
  vars:
    ip: "{{ ansible_default_ipv4.address }}/{{ansible_default_ipv4.netmask }}"

- name: Get version and build from localhost vars
  set_fact:
    version: "{{ hostvars.localhost.version }}"
    build: "{{ hostvars.localhost.build }}"

- name: Get pullsecret from localhost vars
  set_fact:
    pullsecret: "{{ hostvars.localhost.pull_secret| to_json }}"
  no_log: true
