---
- name: "Create SriovOperatorConfig"
  community.kubernetes.k8s:
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovOperatorConfig
      metadata:
        name: default
        namespace: openshift-sriov-network-operator
      spec:
        enableInjector: true
        enableOperatorWebhook: true
        logLevel: 2

- name: "Disable SR-IOV Draining in SNO"
  community.kubernetes.k8s:
    definition:
      apiVersion: sriovnetwork.openshift.io/v1
      kind: SriovOperatorConfig
      metadata:
        name: default
        namespace: openshift-sriov-network-operator
      spec:
        disableDrain: true
  when:
    - install_type is defined
    - install_type == "sno"

- name: "Add SRIOV label to worker nodes"
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ node_fqdn.split('.')[0] }}"
        labels:
          feature.node.kubernetes.io/network-sriov.capable: "true"
  loop: "{{ dci_compute_hosts }}"
  loop_control:
    loop_var: node_fqdn
  when:
    - dci_compute_hosts | length > 0

- name: "Check SriovNetworkNodeState application for all workers"
  include_role:
    name: redhatci.ocp.check_resource
  vars:
    resource_to_check: "SriovNetworkNodeState"
    check_wait_retries: 300
    check_wait_delay: 10
...
